bridges = []
persistence_dir = ''

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = 'dist/blog_core.dna.json'
hash = 'QmQB4dDn7ShJaDEg1UGb3AYypTLSN5RX18sKf2vRUBrHRE'
id = '__blog_core'

[[instances]]
agent = 'hc-run-agent'
dna = '__blog_core'
id = '__blog_core'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = false
choose_free_port = false
id = 'blog_core_ui'

[[interfaces.instances]]
alias = 'test-instance'
id = '__blog_core'

[interfaces.driver]
port = 50000
type = 'websocket'

[[ui_bundles]]
id = 'blog_core_ui'
root_dir = '../blog_gui'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'blog_core_ui'
dna_interface = 'blog_core_ui'
id = 'blog_core_ui'
port = 8888
reroute_to_root = false

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
